FROM node:16.14.0

ARG NODE_ENV
ARG DATABASE
ARG USERNAME
ARG PASSWORD
ARG PORT
ARG HOST
ARG JWT_SECRET_KEY
ARG JWT_EXPIRE_IN
ARG MYSQL_DEFAULT

ENV NODE_ENV=$NODE_ENV
ENV DATABASE=$DATABASE
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD
ENV PORT=$PORT
ENV HOST=$HOST
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV JWT_EXPIRE_IN=$JWT_EXPIRE_IN
ENV MYSQL_DEFAULT=$MYSQL_DEFAULT


WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install --force
COPY . .
RUN yarn build

EXPOSE ${PORT}
CMD [ "yarn", "start" ]